import { getSupabaseClient } from '@/lib/supabase';
function client(){return getSupabaseClient();}function unwrap<T>(data:T|null,error:{message:string}|null):T{if(error)throw new Error(error.message);if(data==null)throw new Error('Enterprise service returned no data.');return data;}
export async function getEnterpriseControlPlaneSnapshot(businessId:string,windowDays=30){const{data,error}=await client().rpc('enterprise_control_plane_snapshot',{p_business_id:businessId,p_window_days:windowDays});return unwrap(data as Record<string,unknown>|null,error);}
export async function listOwnedEnterpriseNetworks(businessId:string){const{data,error}=await client().rpc('enterprise_list_owned_networks',{p_business_id:businessId});return unwrap((data??[]) as Array<Record<string,unknown>>,error);}
export async function listEnterpriseNetworkMembers(networkId:string){const{data,error}=await client().rpc('enterprise_list_network_members',{p_network_id:networkId});return unwrap((data??[]) as Array<Record<string,unknown>>,error);}
export async function listEnterpriseNetworkCampaigns(networkId:string){const{data,error}=await client().rpc('enterprise_list_network_campaigns',{p_network_id:networkId});return unwrap((data??[]) as Array<Record<string,unknown>>,error);}
export async function createEnterpriseCampaign(networkId:string,input:{name:string;campaignType:string;goal:string}){const{data,error}=await client().rpc('create_enterprise_partner_campaign',{p_network_id:networkId,p_name:input.name,p_campaign_type:input.campaignType,p_goal:input.goal});return unwrap(data,error);}
export async function updateEnterpriseCampaign(campaignId:string,input:{name:string;campaignType:string;goal:string;status:string}){const{data,error}=await client().rpc('enterprise_update_campaign',{p_campaign_id:campaignId,p_name:input.name,p_campaign_type:input.campaignType,p_goal:input.goal,p_status:input.status});return unwrap(data,error);}
export async function activateEnterpriseCampaign(campaignId:string){const{data,error}=await client().rpc('activate_enterprise_partner_campaign',{p_campaign_id:campaignId});return unwrap(data,error);}
export async function pauseEnterpriseCampaign(campaignId:string){const{data,error}=await client().rpc('pause_enterprise_partner_campaign',{p_campaign_id:campaignId});return unwrap(data,error);}
export async function deleteEnterpriseCampaign(campaignId:string){const{data,error}=await client().rpc('enterprise_delete_campaign',{p_campaign_id:campaignId});return unwrap(Boolean(data),error);}
export async function recordEnterpriseCampaignOutcome(campaignId:string,partnerBusinessId:string,input:{visits?:number;checkIns?:number;reviews?:number;preferredUses?:number;accessRedemptions?:number;promotionRedemptions?:number;attributedUsers?:number;pointsAwarded?:number}){const{data,error}=await client().rpc('record_enterprise_partner_campaign_outcome',{p_campaign_id:campaignId,p_partner_business_id:partnerBusinessId,p_visits:input.visits??0,p_check_ins:input.checkIns??0,p_reviews:input.reviews??0,p_preferred_uses:input.preferredUses??0,p_access_redemptions:input.accessRedemptions??0,p_promotion_redemptions:input.promotionRedemptions??0,p_attributed_users:input.attributedUsers??0,p_points_awarded:input.pointsAwarded??0});return unwrap(data,error);}
